"""Init

Revision ID: 45659d105d91
Revises: 
Create Date: 2026-09-23 00:39:00.351064
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45659d105d91'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('link', sa.String(length=1000), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('wing_id', sa.String(length=50), nullable=True),
    sa.Column('submitted_by_id', sa.Integer(), nullable=True),
    sa.Column('upvotes', sa.Integer(), nullable=False),
    sa.Column('difficulty_level', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_wing_id'), 'resources', ['wing_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('college_id', sa.String(length=100), nullable=True),
    sa.Column('codeforces_handle', sa.String(length=100), nullable=True),
    sa.Column('codechef_handle', sa.String(length=100), nullable=True),
    sa.Column('github_handle', sa.String(length=100), nullable=True),
    sa.Column('kaggle_handle', sa.String(length=100), nullable=True),
    sa.Column('ctf_handle', sa.String(length=100), nullable=True),
    sa.Column('wings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('codeforces_rating', sa.Integer(), nullable=False),
    sa.Column('codechef_rating', sa.Integer(), nullable=False),
    sa.Column('total_solved', sa.Integer(), nullable=False),
    sa.Column('github_repos', sa.Integer(), nullable=False),
    sa.Column('axios_rating', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('query_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('flag_reason', sa.String(length=255), nullable=True),
    sa.Column('domain_predicted', sa.String(length=50), nullable=True),
    sa.Column('domain_actual', sa.String(length=50), nullable=True),
    sa.Column('response_leaked_solution', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_logs_user_id'), 'query_logs', ['user_id'], unique=False)
    op.create_table('shadow_memories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('concept', sa.String(length=255), nullable=False),
    sa.Column('proficiency', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('mistake_count', sa.Integer(), nullable=False),
    sa.Column('decay_rate', sa.Float(), nullable=False),
    sa.Column('last_noted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shadow_memories_user_id'), 'shadow_memories', ['user_id'], unique=False)
    op.create_table('upsolve_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('problem_url', sa.String(length=500), nullable=True),
    sa.Column('problem_name', sa.String(length=255), nullable=True),
    sa.Column('contest_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upsolve_tasks_user_id'), 'upsolve_tasks', ['user_id'], unique=False)
    op.create_table('routing_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=True),
    sa.Column('sub_task', sa.Text(), nullable=True),
    sa.Column('predicted_domain', sa.String(length=50), nullable=False),
    sa.Column('validated_domain', sa.String(length=50), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['query_id'], ['query_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routing_logs')
    op.drop_index(op.f('ix_upsolve_tasks_user_id'), table_name='upsolve_tasks')
    op.drop_table('upsolve_tasks')
    op.drop_index(op.f('ix_shadow_memories_user_id'), table_name='shadow_memories')
    op.drop_table('shadow_memories')
    op.drop_index(op.f('ix_query_logs_user_id'), table_name='query_logs')
    op.drop_table('query_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_resources_wing_id'), table_name='resources')
    op.drop_table('resources')
    # ### end Alembic commands ###
